import random
import string
from datetime import datetime, timedelta
import json
import requests
from flask import Flask, jsonify, request, redirect
import os
import logging

app = Flask(__name__)

# Define the path for persistent storage (e.g., in Vercel's file system)
DATABASE_FILE = "/tmp/listurl.json"

# Discord Webhook URL
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1307833033214263371/LwKikJE1Xd_tUMqjmPlXXPEovhWdnanCazOurkqmddrUgCqbYRAoDZTCWIncY-2P2z6O"

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# Function to load URL mappings from the file
def load_url_mappings():
    if os.path.exists(DATABASE_FILE):
        with open(DATABASE_FILE, 'r') as file:
            try:
                return json.load(file)
            except json.JSONDecodeError:
                return {}
    return {}

# Function to save URL mappings to the file
def save_url_mappings(data):
    with open(DATABASE_FILE, 'w') as file:
        json.dump(data, file, indent=4)

# Function to generate short URL codes
def generate_short_code(length=6):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def send_discord_log(details):
    """Send detailed log to Discord."""
    payload = {
        "embeds": [
            {
                "title": "API Log",
                "fields": [
                    {"name": "Time", "value": details.get("time"), "inline": True},
                    {"name": "Status Code", "value": details.get("status_code"), "inline": True},
                    {"name": "Request Path", "value": details.get("request_path"), "inline": True},
                    {"name": "Host", "value": details.get("host"), "inline": True},
                    {"name": "Execution Time", "value": details.get("execution_time"), "inline": True},
                    {"name": "Memory Used", "value": details.get("memory_used"), "inline": True},
                ],
                "color": 3447003,  # Blue
                "footer": {"text": "Generated by Flask API"},
                "timestamp": datetime.utcnow().isoformat(),
            }
        ]
    }
    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json=payload, timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        logging.error(f"Failed to send log to Discord: {e}")

# Endpoint 1: Short URL creation
@app.route('/api/shorturl', methods=['POST'])
def create_short_url():
    start_time = datetime.utcnow()

    try:
        data = request.get_json()
        original_url = data.get('originalUrl')
        custom_name = data.get('customName')

        if not original_url:
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": 400,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": 400,
                "error": "Parameter 'originalUrl' is required."
            }), 400

        url_mapping = load_url_mappings()

        if custom_name:
            short_code = custom_name
            if short_code in url_mapping:
                send_discord_log({
                    "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                    "status_code": 400,
                    "request_path": request.path,
                    "host": request.host,
                    "execution_time": "0 ms",
                    "memory_used": "N/A",
                })
                return jsonify({
                    "status": 400,
                    "error": "Custom name already taken."
                }), 400
        else:
            short_code = generate_short_code()
            while short_code in url_mapping:
                short_code = generate_short_code()

        expiration_date = datetime.now() + timedelta(days=30)
        url_mapping[short_code] = {
            "originalUrl": original_url,
            "expirationDate": expiration_date.isoformat()
        }

        save_url_mappings(url_mapping)

        short_url = f"https://www.youga.my.id/{short_code}"

        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return jsonify({
            "status": "success",
            "data": {
                "originalUrl": original_url,
                "shortUrl": short_url,
                "customName": custom_name or short_code,
                "expirationDate": expiration_date.isoformat()
            }
        })

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

# Endpoint 2: Redirect to original URL
@app.route('/<short_code>', methods=['GET'])
def redirect_to_original(short_code):
    start_time = datetime.utcnow()

    try:
        url_mapping = load_url_mappings()
        url_data = url_mapping.get(short_code)

        if not url_data:
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": 404,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": 404,
                "error": "Short URL not found."
            }), 404

        expiration_date = datetime.fromisoformat(url_data["expirationDate"])
        if datetime.now() > expiration_date:
            del url_mapping[short_code]
            save_url_mappings(url_mapping)
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": 410,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": 410,
                "error": "This short URL has expired."
            }), 410

        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return redirect(url_data["originalUrl"])

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

# Endpoint 3: Spotify API Proxy
@app.route('/api/spotify', methods=['GET'])
def spotify():
    start_time = datetime.utcnow()

    message = request.args.get('message')

    if not message:
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 400,
            "request_path": request.path,
            "host": request.host,
            "execution_time": "0 ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": 400,
            "creator": "Astri",
            "error": "Parameter 'message' is required."
        }), 400

    api_url = f"https://api.spotify.com/v1/search?q={message}&type=track"
    headers = {"Authorization": "Bearer YOUR_SPOTIFY_API_TOKEN"}
    try:
        response = requests.get(api_url, headers=headers)
        if response.status_code != 200:
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": response.status_code,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": response.status_code,
                "error": "Error fetching Spotify data"
            }), response.status_code

        data = response.json()
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return jsonify(data)

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

# Endpoint 4: Threads (simulated)
@app.route('/api/threads', methods=['GET'])
def threads():
    start_time = datetime.utcnow()

    try:
        response = {"threads": [{"id": 1, "name": "Thread 1"}, {"id": 2, "name": "Thread 2"}]}
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return jsonify(response)

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

# Endpoint 5: Translate (simulated)
@app.route('/api/translate', methods=['GET'])
def translate():
    start_time = datetime.utcnow()

    try:
        text = request.args.get("text")
        target_lang = request.args.get("target_lang", "en")

        if not text:
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": 400,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": 400,
                "error": "Parameter 'text' is required."
            }), 400

        response = {"translatedText": text[::-1]}  # Simulate reverse translation
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return jsonify(response)

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

# Endpoint 6: Text-to-Speech (simulated)
@app.route('/api/ttstalk', methods=['GET'])
def ttstalk():
    start_time = datetime.utcnow()

    try:
        text = request.args.get("text")

        if not text:
            send_discord_log({
                "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "status_code": 400,
                "request_path": request.path,
                "host": request.host,
                "execution_time": "0 ms",
                "memory_used": "N/A",
            })
            return jsonify({
                "status": 400,
                "error": "Parameter 'text' is required."
            }), 400

        response = {"speech": f"Speaking: {text}"}
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        memory_used = f"{random.randint(50, 100)} MB"
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 200,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": memory_used,
        })

        return jsonify(response)

    except Exception as e:
        execution_time = (datetime.utcnow() - start_time).total_seconds() * 1000
        send_discord_log({
            "time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "status_code": 500,
            "request_path": request.path,
            "host": request.host,
            "execution_time": f"{execution_time:.2f} ms",
            "memory_used": "N/A",
        })
        return jsonify({
            "status": "error",
            "error": "Error occurred"
        }), 500

if __name__ == "__main__":
    app.run(debug=True)
